# Generated by Django 5.2.3 on 2025-06-13 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_employee', models.CharField(max_length=100)),
                ('surname_employee', models.CharField(max_length=100)),
                ('mail_employee', models.EmailField(max_length=254)),
                ('card_employee', models.CharField(max_length=20, unique=True)),
                ('code_employee', models.CharField(max_length=20, unique=True)),
                ('imagen_employee', models.ImageField(blank=True, null=True, upload_to='trabajadores/')),
                ('employee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='Company.company')),
            ],
        ),
    ]
