# Generated by Django 5.2.3 on 2025-06-25 20:34

import Applications.Employee.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_employee', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex="^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s'-]+$")])),
                ('surname_employee', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex="^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s'-]+$")])),
                ('mail_employee', models.EmailField(error_messages={'unique': 'Este correo ya está registrado.'}, max_length=254, unique=True)),
                ('card_employee', models.CharField(error_messages={'unique': 'Esta cédula ya está registrada.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('code_employee', models.CharField(error_messages={'unique': 'Este código ya está registrado.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]{4,10}$', message='El código solo debe contener letras mayúsculas, números y guiones. Debe tener entre 4 y 10 caracteres.')])),
                ('imagen_employee', models.ImageField(blank=True, null=True, upload_to='employees/', validators=[Applications.Employee.models.validar_extension, Applications.Employee.models.validar_tamano])),
            ],
        ),
    ]
