# Generated by Django 5.2.3 on 2025-06-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_remove_employee_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='imagen_employee',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/trabajadores/'),
        ),
    ]
