# Generated by Django 5.2.3 on 2025-06-24 06:29

import Applications.Employee.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employee_imagen_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='card_employee',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{13}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code_employee',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]{4,20}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='imagen_employee',
            field=models.ImageField(blank=True, null=True, upload_to='employees/', validators=[Applications.Employee.models.validar_extension, Applications.Employee.models.validar_tamano]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mail_employee',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_employee',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex='^[A-Za-z0-9\\s\\.\\-&]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname_employee',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex='^[A-Za-z0-9\\s\\.\\-&]+$')]),
        ),
    ]
