# Generated by Django 5.2.3 on 2025-06-24 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_employee_card_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name_employee',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex="^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s'-]+$")]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname_employee',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex="^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s'-]+$")]),
        ),
    ]
