# Generated by Django 5.2.3 on 2025-06-24 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_alter_employee_name_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='card_employee',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code_employee',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]{4,10}$')]),
        ),
    ]
