# Generated by Django 5.2.3 on 2025-06-24 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_alter_employee_card_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='card_employee',
            field=models.CharField(error_messages={'unique': 'Esta cédula ya está registrada.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code_employee',
            field=models.CharField(error_messages={'unique': 'Este código ya está registrado.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]{4,10}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mail_employee',
            field=models.EmailField(error_messages={'unique': 'Este correo ya está registrado.'}, max_length=254, unique=True),
        ),
    ]
