# Generated by Django 5.2.3 on 2025-06-24 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_alter_employee_card_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='code_employee',
            field=models.CharField(error_messages={'unique': 'Este código ya está registrado.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]{4,10}$', message='El código solo debe contener letras mayúsculas, números y guiones. Debe tener entre 4 y 10 caracteres.')]),
        ),
    ]
