# Generated by Django 5.2.3 on 2025-06-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100)),
                ('address_company', models.CharField(max_length=100)),
                ('mission_company', models.TextField()),
                ('vision_company', models.TextField()),
                ('founding_company', models.PositiveIntegerField()),
                ('ruc_company', models.CharField(max_length=13, unique=True)),
                ('imagen_company', models.ImageField(blank=True, null=True, upload_to='empresas/')),
            ],
        ),
    ]
