# Generated by Django 5.2.3 on 2025-06-22 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_company_ruc_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ruc_company',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{13}$')]),
        ),
    ]
