# Generated by Django 5.2.3 on 2025-06-22 16:10

import Applications.Company.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_alter_company_ruc_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_company',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='founding_company',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='imagen_company',
            field=models.ImageField(blank=True, null=True, upload_to='company/', validators=[Applications.Company.models.validar_extension_imagen, Applications.Company.models.validar_tamano_imagen]),
        ),
        migrations.AlterField(
            model_name='company',
            name='mission_company',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_company',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Solo se permiten letras, números, espacios y . - &', regex='^[A-Za-z0-9\\s\\.\\-&]+$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='vision_company',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
