# Generated by Django 5.2.3 on 2025-06-22 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_alter_company_address_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name_company',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex='^[A-Za-z0-9\\s\\.\\-&]+$')]),
        ),
    ]
