# Generated by Django 5.2.3 on 2025-06-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_supplier', models.CharField(max_length=200)),
                ('description_supplier', models.TextField()),
                ('phone_supplier', models.CharField(max_length=20)),
                ('country_supplier', models.CharField(max_length=100)),
                ('mail_supplier', models.EmailField(max_length=254)),
                ('address_supplier', models.TextField()),
            ],
        ),
    ]
