# Generated by Django 5.2.3 on 2025-06-25 20:34

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_supplier', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex="^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s'-]+$")])),
                ('description_supplier', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descripción')),
                ('phone_supplier', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Este número ya está registrado.'}, max_length=128, region=None, unique=True)),
                ('country_supplier', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex="^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s'-]+$")], verbose_name='País')),
                ('mail_supplier', models.EmailField(error_messages={'unique': 'Este correo ya está registrado.'}, max_length=254, unique=True)),
                ('address_supplier', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(regex="^(?=.*[A-Za-zÁÉÍÓÚáéíóúÑñ])[A-Za-z0-9ÁÉÍÓÚáéíóúÑñ\\s.,'\\-#°/]+$")])),
            ],
        ),
    ]
