# Generated by Django 5.2.3 on 2025-06-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address_supplier',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country_supplier',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='description_supplier',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mail_supplier',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name_supplier',
            field=models.CharField(max_length=200, verbose_name='Nombre del Proveedor'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_supplier',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
