# Generated by Django 5.2.3 on 2025-06-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
    ]
