# Generated by Django 5.2.3 on 2025-06-25 01:24

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address_supplier',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(regex="^(?=.*[A-Za-zÁÉÍÓÚáéíóúÑñ])[A-Za-z0-9ÁÉÍÓÚáéíóúÑñ\\s.,'\\-#°/]+$")]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country_supplier',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex="^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s'-]+$")], verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='description_supplier',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mail_supplier',
            field=models.EmailField(error_messages={'unique': 'Este correo ya está registrado.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name_supplier',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex="^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s'-]+$")]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_supplier',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Este número ya está registrado.'}, max_length=128, region=None, unique=True),
        ),
    ]
