# Generated by Django 5.2.3 on 2025-06-25 20:34

import Applications.Products.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_products', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex="^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s'-]+$")])),
                ('description_products', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('price_products', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('iva_products', models.IntegerField(choices=[(15, '15%'), (0, '0%')])),
                ('imagen_products', models.ImageField(blank=True, null=True, upload_to='products/', validators=[Applications.Products.models.validar_extension, Applications.Products.models.validar_tamano])),
            ],
        ),
    ]
