# Generated by Django 5.2.3 on 2025-06-20 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_products', models.CharField(max_length=200)),
                ('description_products', models.TextField()),
                ('price_products', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_products', models.IntegerField(choices=[(15, '15%'), (0, '0%')])),
                ('imagen_products', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Supplier.supplier')),
            ],
        ),
    ]
