# Generated by Django 5.2.3 on 2025-06-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='proveedor',
        ),
    ]
